#ifndef TOKENS_H
#define TOKENS_H

#define ARITHMETIC_OP_TOKEN 256
#define LOGICAL_OP_TOKEN 257
#define BITWISE_OP_TOKEN 258
#define ASSIGNMENT_OP_TOKEN 259
#define RESERVED_WORD_TOKEN 260
#define IDENTIFIER_TOKEN 261
#define INT_CONST_TOKEN 262
#define FLOAT_CONST_TOKEN 263
#define STRING_LITERAL_TOKEN 264
#define CHAR_CONST_TOKEN 265
#define L_PARENTHESIS_TOKEN 266
#define R_PARENTHESIS_TOKEN 267
#define L_CURLY_BRACE_TOKEN 268
#define R_CURLY_BRACE_TOKEN 269
#define L_SQUARE_BRACKET_TOKEN 270
#define R_SQUARE_BRACKET_TOKEN 271
#define SEMICOLON_TOKEN 272
#define COMMA_TOKEN 273
#define HEADER_FILE_TOKEN 274
#define MACRO_TOKEN 275
#define ADDRESS_OF_TOKEN 276
#define POINTER_TOKEN 277
#define COMMENT_TOKEN 278
#define EOF_TOKEN 279
#define UNKNOWN_TOKEN 280
#define RELATIONAL_OP_TOKEN 281
#define ERROR_TOKEN 500

#endif